const os = require('os');
const path = require('path');
const fs = require('fs');
const { spawnSync } = require('child_process');

const appDataDir = process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local');

// The app under test is pointed at a FULLY ISOLATED test database via the
// DB_PATH env override. The live store DB (%LOCALAPPDATA%\RMS\local.db) is
// NEVER opened, backed up, overwritten, or restored by this harness.
const testDbDir = path.join(appDataDir, 'RMS', 'e2e-test');
const testDbPath = path.join(testDbDir, 'test.db');

exports.config = {
    runner: 'local',
    specs: [
        // orderFlow last: its checkout fires a native print dialog
        // (window.print) that blocks the shared app's JS thread for any
        // spec that runs after it.
        './test/e2e/diag.test.cjs',
        './test/e2e/loginFlow.test.cjs',
        './test/e2e/menuManagement.test.cjs',
        './test/e2e/staffPayroll.test.cjs',
        './test/e2e/settings.test.cjs',
        './test/e2e/printSettings.test.cjs',
        './test/e2e/orderFlow.test.cjs'
    ],
    maxInstances: 1,
    capabilities: [{
        maxInstances: 1,
        browserName: 'tauri',
        'tauri:options': {
            application: process.env.RMS_EXE || 'D:\\RustTarget\\debug\\rms.exe'
        }
    }],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['tauri'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },

    onPrepare: function () {
        // E2E risk mitigation: refuse to start while an autonomous WebDriver
        // app instance (rms.exe with a debug port, running against the LIVE
        // store DB) is already on the machine.
        const check = spawnSync(process.execPath, [path.resolve(__dirname, 'scripts/watchdog.cjs'), 'status'], {
            encoding: 'utf8',
            timeout: 30000,
            windowsHide: true
        });
        if (check.status !== 0) {
            console.error('\nERROR: store DB is currently threatened by an autonomous WebDriver process.');
            console.error(check.stdout || '');
            console.error(check.stderr || ''); // Include stderr so we see the actual process
            console.error('Run `npm run watchdog cleanup` to kill it and restore the store DB, then retry.\n');
            process.exit(1);
        }

        // Seed source is regenerated by `node test/e2e/setup.cjs` (npm run test:e2e does this).
        const seedSource = path.resolve(__dirname, 'test.db');
        if (!fs.existsSync(seedSource)) {
            console.error('ERROR: test.db not found. Run `node test/e2e/setup.cjs` first (npm run test:e2e does this).');
            process.exit(1);
        }
        fs.mkdirSync(testDbDir, { recursive: true });
        fs.copyFileSync(seedSource, testDbPath);

        // Expose the isolated DB path to the Tauri app. IMPORTANT: this must
        // happen in onPrepare, NOT beforeSession — the tauri-service spawns the
        // app during its own onPrepare (after this hook), so the app's Rust
        // side reads DB_PATH from the environment at startup. Setting it in
        // beforeSession is too late (the app is already running by then) and
        // would make the suite silently operate against the LIVE store DB.
        process.env.DB_PATH = testDbPath;
    },

    beforeSession: function () {
        // Expose the isolated DB path to the specs.
        process.env.E2E_DB_PATH = testDbPath;
        process.env.DB_PATH = testDbPath;
    },

    afterSession: function () {
        // Remove only the isolated test directory. The live store DB is untouched.
        try {
            fs.rmSync(testDbDir, { recursive: true, force: true });
        } catch (e) {
            console.warn('Could not clean isolated test dir:', e.message);
        }
    }
};
