const os = require('os');
const path = require('path');
const fs = require('fs');
const { spawn } = require('child_process');

let edgeDriver;
const appDataDir = process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local');

// The app under test is pointed at a FULLY ISOLATED test database via the
// DB_PATH env override. The live store DB (%LOCALAPPDATA%\RMS\local.db) is
// NEVER opened, backed up, overwritten, or restored by this harness.
const testDbDir = path.join(appDataDir, 'RMS', 'e2e-test');
const testDbPath = path.join(testDbDir, 'test.db');

exports.config = {
    runner: 'local',
    specs: [
        './test/e2e/**/*.test.cjs'
    ],
    maxInstances: 1,
    capabilities: [{
        maxInstances: 1,
        browserName: 'MicrosoftEdge',
        'ms:edgeOptions': {
            binary: process.env.RMS_EXE || 'D:\\RustTarget\\debug\\rms.exe',
            args: ['--remote-debugging-port=9222']
        }
    }],
    port: 4444,
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: [],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },

    beforeSession: function () {
        // Seed source is regenerated by `node test/e2e/setup.cjs` (npm run test:e2e does this).
        const seedSource = path.resolve(__dirname, 'test.db');
        if (!fs.existsSync(seedSource)) {
            console.error('ERROR: test.db not found. Run `node test/e2e/setup.cjs` first (npm run test:e2e does this).');
            process.exit(1);
        }
        fs.mkdirSync(testDbDir, { recursive: true });
        fs.copyFileSync(seedSource, testDbPath);
        // Expose the isolated DB path to the spec (same path the app writes to).
        process.env.E2E_DB_PATH = testDbPath;

        const driverPath = process.env.EDGEDRIVER_PATH || path.resolve(__dirname, 'msedgedriver.exe');
        edgeDriver = spawn(driverPath, ['--port=4444'], {
            stdio: [null, process.stdout, process.stderr],
            env: {
                ...process.env,
                DB_PATH: testDbPath,
                WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS: '--remote-debugging-port=9222'
            }
        });

        edgeDriver.on('error', (err) => {
            console.error('\nERROR: Failed to start msedgedriver.');
        });
    },

    afterSession: function () {
        if (edgeDriver) {
            edgeDriver.kill();
        }
        // Remove only the isolated test directory. The live store DB is untouched.
        try {
            fs.rmSync(testDbDir, { recursive: true, force: true });
        } catch (e) {
            console.warn('Could not clean isolated test dir:', e.message);
        }
    }
}
