#![allow(dead_code, unused_variables, non_snake_case)]

use base64::{engine::general_purpose::STANDARD as BASE64, Engine};
use chrono::NaiveDate;
use rsa::pkcs1v15::{Signature, VerifyingKey};
use rsa::pkcs8::DecodePublicKey;
use rsa::signature::Verifier;
use rsa::RsaPublicKey;
use serde::Serialize;
use sha2::Sha256;
use sysinfo::System;

use std::sync::OnceLock;

static HWID_CACHE: OnceLock<String> = OnceLock::new();

/// Generates a hardware-bound identifier from the machine's hostname, MAC address, and Windows MachineGuid.
/// This value is 100% deterministic and permanently stable across reinstalls on the same device.
pub fn get_hwid() -> String {
    HWID_CACHE.get_or_init(|| {
        let hostname = System::host_name()
            .or_else(|| std::env::var("COMPUTERNAME").ok())
            .unwrap_or_else(|| "UNKNOWN-HOST".to_string());

        let mac = get_primary_mac().unwrap_or_else(|| "00:00:00:00:00:00".to_string());
        let machine_guid = get_windows_machine_guid().unwrap_or_else(|| "UNKNOWN-GUID".to_string());

        use sha2::Digest;
        let mut hasher = sha2::Sha256::new();
        hasher.update(format!("{}|{}|{}", hostname, mac, machine_guid));
        let result = hasher.finalize();

        let hex: String = result.iter().take(16).map(|b| format!("{:02X}", b)).collect();

        format!(
            "{}-{}-{}-{}",
            &hex[0..4],
            &hex[4..8],
            &hex[8..12],
            &hex[12..16]
        )
    }).clone()
}

/// Retrieves the primary MAC address deterministically by sorting all interface MACs.
fn get_primary_mac() -> Option<String> {
    let networks = sysinfo::Networks::new_with_refreshed_list();
    let mut macs: Vec<String> = Vec::new();

    for (_name, network) in &networks {
        let mac_str = network.mac_address().to_string().to_uppercase();
        if !mac_str.is_empty() && mac_str != "00:00:00:00:00:00" && mac_str.contains(':') {
            macs.push(mac_str);
        }
    }

    if !macs.is_empty() {
        macs.sort(); // Sort deterministically so interface order is 100% stable
        return Some(macs[0].clone());
    }

    #[cfg(target_os = "windows")]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x08000000;
        
        let mut cmd = std::process::Command::new("getmac");
        cmd.args(["/FO", "CSV", "/NH"]);
        cmd.creation_flags(CREATE_NO_WINDOW);
        
        if let Ok(output) = cmd.output() {
            let stdout = String::from_utf8_lossy(&output.stdout);
            for line in stdout.lines() {
                let parts: Vec<&str> = line.split(',').collect();
                if let Some(mac_field) = parts.first() {
                    let mac = mac_field.trim().trim_matches('"');
                    if !mac.is_empty() && mac != "N/A" && mac.contains('-') {
                        macs.push(mac.replace('-', ":").to_uppercase());
                    }
                }
            }
        }
        if !macs.is_empty() {
            macs.sort();
            return Some(macs[0].clone());
        }
    }

    None
}

/// Retrieves the permanent Windows MachineGuid from the registry for stable hardware identification.
fn get_windows_machine_guid() -> Option<String> {
    #[cfg(target_os = "windows")]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x08000000;

        let mut cmd = std::process::Command::new("reg");
        cmd.args(["query", "HKLM\\SOFTWARE\\Microsoft\\Cryptography", "/v", "MachineGuid"]);
        cmd.creation_flags(CREATE_NO_WINDOW);

        if let Ok(output) = cmd.output() {
            let stdout = String::from_utf8_lossy(&output.stdout);
            for line in stdout.lines() {
                if line.contains("MachineGuid") {
                    let parts: Vec<&str> = line.split_whitespace().collect();
                    if let Some(guid) = parts.last() {
                        return Some(guid.to_string());
                    }
                }
            }
        }
    }
    None
}

// ─── Embedded Public Key ────────────────────────────────────────────────────
// This public key is used to verify license keys signed by the owner's private key.
// Replace this with your actual public key generated by the keygen script.

const PUBLIC_KEY_PEM: &str = "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnfpuwXZ872GX2c/qE4KT
8UnLHDR+BfJuW8aT/bNEU6Q9EEi9/qFAdV/jPtud/IJNSfBY/jUyFszSSDAiFuyI
sh8LWUm/673ooXSQSZeNBvDpKjdDsNrL3G0R1rf8bP+nEuYKuE+ih/riUeH+kYee
Sc5zYC93pnBv4pKZnGUL+N3LdqAW1H2yzpeLScv+OzaR8N/g4iSiKes9Gv1fHNRT
SIjY9XSJMo8SAY6x1b+qT9D1CpEdEP/4O1W61ha0wSadzPv1kPPmKVnfygUS7j9o
OLYwOj+eubKpZmpiMkbGD08NeettFijBwkZZ+SgvrzeqYXbOxC1kfLY7pi+Z3FRv
wwIDAQAB
-----END PUBLIC KEY-----";

// ─── License Key Format ─────────────────────────────────────────────────────
// A license key is a Base64 string that decodes to:
//   PAYLOAD\n
//   SIGNATURE
//
// Where PAYLOAD is: HWID|EXPIRY_DATE (e.g., "A1B2-C3D4-E5F6-G7H8|2025-12-31")
// And SIGNATURE is the RSA-SHA256 signature of PAYLOAD, also Base64 encoded.

#[derive(Serialize)]
pub struct LicenseStatus {
    pub valid: bool,
    pub hwid: String,
    pub message: String,
    pub expiry_date: Option<String>,
    pub days_remaining: Option<i64>,
}

/// Verifies a license key against the current machine's HWID and today's date.
pub fn verify_license_key(key_string: &str) -> LicenseStatus {
    let hwid = get_hwid();

    // Decode the key from Base64
    let decoded = match BASE64.decode(key_string.trim()) {
        Ok(d) => d,
        Err(_) => {
            return LicenseStatus {
                valid: false,
                hwid,
                message: "Invalid license key format.".to_string(),
                expiry_date: None,
                days_remaining: None,
            };
        }
    };

    let decoded_str = match String::from_utf8(decoded) {
        Ok(s) => s,
        Err(_) => {
            return LicenseStatus {
                valid: false,
                hwid,
                message: "Invalid license key encoding.".to_string(),
                expiry_date: None,
                days_remaining: None,
            };
        }
    };

    // Split into payload and signature
    let parts: Vec<&str> = decoded_str.splitn(2, '\n').collect();
    if parts.len() != 2 {
        return LicenseStatus {
            valid: false,
            hwid,
            message: "Malformed license key.".to_string(),
            expiry_date: None,
            days_remaining: None,
        };
    }

    let payload = parts[0];
    let signature_b64 = parts[1];

    // Verify RSA signature
    let pub_key = match RsaPublicKey::from_public_key_pem(PUBLIC_KEY_PEM) {
        Ok(k) => k,
        Err(_) => {
            return LicenseStatus {
                valid: false,
                hwid,
                message: "Internal error: invalid public key configuration.".to_string(),
                expiry_date: None,
                days_remaining: None,
            };
        }
    };

    let sig_bytes = match BASE64.decode(signature_b64.trim()) {
        Ok(s) => s,
        Err(_) => {
            return LicenseStatus {
                valid: false,
                hwid,
                message: "Invalid signature in license key.".to_string(),
                expiry_date: None,
                days_remaining: None,
            };
        }
    };

    let verifying_key = VerifyingKey::<Sha256>::new(pub_key);
    let signature = match Signature::try_from(sig_bytes.as_slice()) {
        Ok(s) => s,
        Err(_) => {
            return LicenseStatus {
                valid: false,
                hwid,
                message: "Corrupted signature in license key.".to_string(),
                expiry_date: None,
                days_remaining: None,
            };
        }
    };

    if verifying_key.verify(payload.as_bytes(), &signature).is_err() {
        return LicenseStatus {
            valid: false,
            hwid,
            message: "License key signature verification failed. This key is invalid or tampered with.".to_string(),
            expiry_date: None,
            days_remaining: None,
        };
    }

    // Signature is valid — now check payload contents
    let payload_parts: Vec<&str> = payload.splitn(2, '|').collect();
    if payload_parts.len() != 2 {
        return LicenseStatus {
            valid: false,
            hwid,
            message: "Malformed license payload.".to_string(),
            expiry_date: None,
            days_remaining: None,
        };
    }

    let key_hwid = payload_parts[0];
    let key_expiry = payload_parts[1];

    // Check HWID match
    if key_hwid != hwid {
        return LicenseStatus {
            valid: false,
            hwid,
            message: "This license key was issued for a different machine.".to_string(),
            expiry_date: Some(key_expiry.to_string()),
            days_remaining: None,
        };
    }

    // Check expiry
    let expiry = match NaiveDate::parse_from_str(key_expiry, "%Y-%m-%d") {
        Ok(d) => d,
        Err(_) => {
            return LicenseStatus {
                valid: false,
                hwid,
                message: "Invalid expiry date in license key.".to_string(),
                expiry_date: Some(key_expiry.to_string()),
                days_remaining: None,
            };
        }
    };

    let today = chrono::Local::now().date_naive();
    let days_remaining = (expiry - today).num_days();

    if days_remaining < 0 {
        return LicenseStatus {
            valid: false,
            hwid,
            message: format!(
                "License expired on {}. Please contact your vendor for renewal.",
                key_expiry
            ),
            expiry_date: Some(key_expiry.to_string()),
            days_remaining: Some(days_remaining),
        };
    }

    LicenseStatus {
        valid: true,
        hwid,
        message: format!("License is active. {} days remaining.", days_remaining),
        expiry_date: Some(key_expiry.to_string()),
        days_remaining: Some(days_remaining),
    }
}

// ─── Tauri Commands ─────────────────────────────────────────────────────────

use std::sync::Mutex;
use std::time::{Duration, Instant};

struct LicenseCache {
    checked_at: Instant,
    valid: bool,
}

static LICENSE_CACHE: Mutex<Option<LicenseCache>> = Mutex::new(None);

/// Fast boolean license check used by the central `authorize()` gate in lib.rs.
/// Every protected IPC command is blocked unless a valid, unexpired license for
/// this machine is present. The result is cached for a short window so we do
/// not re-read the key and re-verify the RSA signature on every single IPC call.
pub fn is_license_valid() -> bool {
    {
        if let Ok(cache) = LICENSE_CACHE.lock() {
            if let Some(c) = cache.as_ref() {
                if c.checked_at.elapsed() < Duration::from_secs(5) {
                    return c.valid;
                }
            }
        }
    }

    let valid = matches!(check_license_status(), Ok(s) if s.valid);

    if let Ok(mut cache) = LICENSE_CACHE.lock() {
        *cache = Some(LicenseCache {
            checked_at: Instant::now(),
            valid,
        });
    }
    valid
}

/// Invalidates the cached license verdict (called after a successful
/// activation or renewal so the new key takes effect immediately).
pub fn invalidate_license_cache() {
    if let Ok(mut cache) = LICENSE_CACHE.lock() {
        *cache = None;
    }
}

/// Returns the current machine's HWID for display on the License screen.
#[tauri::command]
pub fn get_machine_hwid() -> String {
    get_hwid()
}

/// Checks the license status by reading the stored key from the database.
#[tauri::command]
pub fn check_license_status() -> Result<LicenseStatus, String> {
    let conn = crate::db::get_conn()?;

    let hwid = get_hwid();

    // Try to read the current key from the license table
    let key: Option<String> = conn
        .query_row(
            "SELECT current_key FROM license WHERE id = 1",
            [],
            |row| row.get(0),
        )
        .ok();

    match key {
        Some(k) if !k.is_empty() => {
            let status = verify_license_key(&k);
            if status.valid {
                // Detect clock rollback: the license can only be valid if the
                // current date is not earlier than the last date it validated.
                // Persist today on every successful check.
                let today = chrono::Local::now().format("%Y-%m-%d").to_string();
                let last_validated: Option<String> = conn
                    .query_row(
                        "SELECT last_validated_date FROM license WHERE id = 1",
                        [],
                        |row| row.get(0),
                    )
                    .ok();

                if let Some(prev) = last_validated {
                    if !prev.is_empty() {
                        if let (Ok(prev_date), Ok(today_date)) = (
                            NaiveDate::parse_from_str(&prev, "%Y-%m-%d"),
                            NaiveDate::parse_from_str(&today, "%Y-%m-%d"),
                        ) {
                            if today_date < prev_date {
                                let expiry_date = status.expiry_date.clone();
                                let days_remaining = expiry_date.as_deref().and_then(|d| NaiveDate::parse_from_str(d, "%Y-%m-%d").ok()).map(|exp| (exp - today_date).num_days());
                                return Ok(LicenseStatus {
                                    valid: false,
                                    hwid,
                                    message: "System clock appears to have been rolled back. Please restore the correct date.".to_string(),
                                    expiry_date,
                                    days_remaining,
                                });
                            }
                        }
                    }
                }

                let _ = conn.execute(
                    "UPDATE license SET last_validated_date = ?1 WHERE id = 1",
                    rusqlite::params![today],
                );
            }
            Ok(status)
        }
        _ => Ok(LicenseStatus {
            valid: false,
            hwid,
            message: "No license key found. Please activate your license.".to_string(),
            expiry_date: None,
            days_remaining: None,
        }),
    }
}

/// Activates a license key by verifying it and storing it in the database.
#[tauri::command]
pub fn activate_license(key: String) -> Result<LicenseStatus, String> {
    let status = verify_license_key(&key);

    if !status.valid {
        return Ok(status);
    }

    // Key is valid — store it in the database
    let conn = crate::db::get_conn()?;

    let expiry = status.expiry_date.as_deref().unwrap_or("");
    let now = chrono::Local::now().format("%Y-%m-%d %H:%M:%S").to_string();

    conn.execute(
        "INSERT INTO license (id, current_key, expiry_date, activated_at) VALUES (1, ?1, ?2, ?3) \
         ON CONFLICT(id) DO UPDATE SET current_key = ?1, expiry_date = ?2, activated_at = ?3",
        [&key, expiry, &now.as_str()],
    )
    .map_err(|e| e.to_string())?;

    invalidate_license_cache();

    Ok(status)
}

/// Returns license info for the Settings page (HWID, expiry, activated_at, days remaining).
#[derive(Serialize)]
pub struct LicenseInfo {
    pub hwid: String,
    pub expiry_date: Option<String>,
    pub activated_at: Option<String>,
    pub days_remaining: Option<i64>,
    pub status: String,
}

#[tauri::command]
pub fn get_license_info() -> Result<LicenseInfo, String> {
    let conn = crate::db::get_conn()?;
    let hwid = get_hwid();

    // Read license data from DB
    let result: Option<(Option<String>, Option<String>)> = conn
        .query_row(
            "SELECT expiry_date, activated_at FROM license WHERE id = 1",
            [],
            |row| Ok((row.get(0).ok(), row.get(1).ok())),
        )
        .ok();

    match result {
        Some((expiry_date, activated_at)) => {
            let (days_remaining, status) = if let Some(ref exp) = expiry_date {
                if let Ok(expiry) = NaiveDate::parse_from_str(exp, "%Y-%m-%d") {
                    let today = chrono::Local::now().date_naive();
                    let days = (expiry - today).num_days();
                    if days < 0 {
                        (Some(days), "Expired".to_string())
                    } else {
                        (Some(days), "Active".to_string())
                    }
                } else {
                    (None, "Unknown".to_string())
                }
            } else {
                (None, "No License".to_string())
            };

            Ok(LicenseInfo {
                hwid,
                expiry_date,
                activated_at,
                days_remaining,
                status,
            })
        }
        None => Ok(LicenseInfo {
            hwid,
            expiry_date: None,
            activated_at: None,
            days_remaining: None,
            status: "No License".to_string(),
        }),
    }
}
